package com.HomeLoanApplication.entites;

public enum Status {
	PENDING, APPROVED, WAITING_FOR_FINANCE_APPROVAL, WAITING_FOR_LAND_VERIFICATION_APPROVAL, REJECTED, DOCUMENTS_NOT_UPLOADED, ACCEPTED, REJECTED_BY_ADMIN, REJECTED_BY_LAND_OFFICER, REJECTED_BY_FINANCE_OFFICER
}